{"ip_str": "104.238.182.217", "errors": {"VPN_error": "End Of File (EOF). Exception style platform.\n<pexpect.pty_spawn.spawn object at 0x7f804bc702e0>\ncommand: /usr/sbin/openvpn\nargs: ['/usr/sbin/openvpn', '/home/NetPlatform/configurations/tw2-ovpn-tcp.ovpn']\nbuffer (last 100 chars): b''\nbefore (last 100 chars): b'essage: AUTH_FAILED\\r\\nMon Oct 24 09:58:40 2022 SIGTERM[soft,auth-failure] received, process exiting\\r\\n'\nafter: <class 'pexpect.exceptions.EOF'>\nmatch: None\nmatch_index: None\nexitstatus: 0\nflag_eof: True\npid: 8\nchild_fd: 5\nclosed: False\ntimeout: 30\ndelimiter: <class 'pexpect.exceptions.EOF'>\nlogfile: None\nlogfile_read: None\nlogfile_send: None\nmaxread: 2000\nignorecase: False\nsearchwindowsize: None\ndelaybeforesend: 0.05\ndelayafterclose: 0.1\ndelayafterterminate: 0.1\nsearcher: searcher_re:\n    0: re.compile(b'Initialization Sequence Completed')"}}