{"ip_str": "104.238.182.217", "errors": {"VPN_error": "Timeout exceeded.\n<pexpect.pty_spawn.spawn object at 0x7f75ec8ba2e0>\ncommand: /usr/sbin/openvpn\nargs: ['/usr/sbin/openvpn', '/home/NetPlatform/configurations/vlap-vn2-ovpn-udp.ovpn']\nbuffer (last 100 chars): b'2 UDP link local: (not bound)\\r\\nMon Oct 24 10:44:42 2022 UDP link remote: [AF_INET]172.111.197.4:53\\r\\n'\nbefore (last 100 chars): b'2 UDP link local: (not bound)\\r\\nMon Oct 24 10:44:42 2022 UDP link remote: [AF_INET]172.111.197.4:53\\r\\n'\nafter: <class 'pexpect.exceptions.TIMEOUT'>\nmatch: None\nmatch_index: None\nexitstatus: None\nflag_eof: False\npid: 8\nchild_fd: 5\nclosed: False\ntimeout: 30\ndelimiter: <class 'pexpect.exceptions.EOF'>\nlogfile: None\nlogfile_read: None\nlogfile_send: None\nmaxread: 2000\nignorecase: False\nsearchwindowsize: None\ndelaybeforesend: 0.05\ndelayafterclose: 0.1\ndelayafterterminate: 0.1\nsearcher: searcher_re:\n    0: re.compile(b'Initialization Sequence Completed')"}}